### ISSUE TITLE
Autorun

### ISSUE THREAD

**Issue by Larssta** [robinz-labs/digishow#3]
Can I start the program automatically? So you don't need to press the play button?

**Comment by robinz-labs** [comment]
No, you must press play button to start a digishow link session.  For the automatic feature you mentioned, do you mean you want to run digishow app and start a program in a specified dgs file once the computer operation system started ?

**Comment by Larssta** [comment]
is there a chance to put the show in computer startup, and when you turn on your computer, the show is running automatically without going into the program and press the start button

**Comment by robinz-labs** [comment]
autostart option is added in commit c83d536b4c89b5b141f86b262d48f597d142795d 

![Screen Shot 2022-08-10 at 11 24 18 PM](https://user-images.githubusercontent.com/70817531/183943553-febc2557-3290-4de4-94de-d2e6d5f232a8.png)
